name: XAUT-USDT Trading Bot

on:
  schedule:
    - cron: '*/25 * * * *'  # Jalankan setiap 25 menit
  workflow_dispatch:       # Memungkinkan run manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser textblob pandas requests numpy ta gspread google-auth
        
    - name: Run trading bot
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python trading_bot.py
      
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Trading Bot Failed",
            body: "The trading bot script failed. Please check the logs."
          })