name: XAUT-USDT Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser textblob pandas requests numpy ta gspread google-auth
        pip list  # Print installed packages for debugging
        
    - name: Run trading bot
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "Starting trading bot..."
        python trading_bot.py
        echo "Trading bot finished"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: trading-bot-logs
        path: |
          *.log
          *.txt